### ISSUE TITLE
I dont see the plugin

### ISSUE THREAD

**Issue by DavideCenc** [OctoPrint/OctoPrint-Pushbullet#19]
I istalled the zip version, but i dont see the plug on the left windows under plugin list. It's impossible for me to configure the plugin with token. Same thing with Yamlpatcher.
Are correctly istalled in plugin manager.
some idea?
thanks
python version 2.7.10       octoprint version 1.3.4

**Comment by foosel** [comment]
So it's not showing here?

![image](https://user-images.githubusercontent.com/83657/31490589-cced39d4-af44-11e7-8eb1-1a81ab24987d.png)

What does it say in PluginManager, is it enabled? It will still show up if it's not enabled, but be greyed out slightly.

Please provide your `octoprint.log`, maybe there's some error being thrown.

**Comment by DavideCenc** [comment]
[octoprint.log](https://github.com/OctoPrint/OctoPrint-Pushbullet/files/1384680/octoprint.log)

**Comment by foosel** [comment]
Sorry, the notification about your reply somehow got buried 😕

I see a number of error responses in your log that hint at a problem with your login session. Have you tried logging out and back in? Try also to [refresh your browser cache](http://refreshyourcache.com/en/cache/) to make sure there's nothing weird going on there due to that.

Do you see other plugins (e.g. the Cura Plugin) in the area I highlighted in red or is everything missing from there?

**Comment by foosel** [comment]
Closing due to lack of response.
