### ISSUE TITLE
Image on complete is upside down

### ISSUE THREAD

**Issue by Brictone** [OctoPrint/OctoPrint-Pushbullet#3]
I have to flip my camera image because my camera is mounted upside down.  When pushbullet sends the photo it is sent upside down.  I'm sure it's just snapping an image from the camera but it seems like the plugin just needs to know the settings that were selected in the webcam to take the photo correctly.

**Comment by foosel** [comment]
And then you realize you've managed to forget about a ticket for over a year. *blushes heavily*

So, I've looked into this a bit, and the problem is that in order to do image manipulation (which I'd need to do here) I'd need to pull in an image manipulation library like pillow, wand or jpegtran-cffi. Pillow is somewhat big and not the fastest library, wand-py requires imagemagick to be installed outside of python which I can't really install from a plugin, and jpegtran-cffi depends on libturbojpeg with the same limitations. 

That leaves Pillow. Which means pulling in an 11MB zip file (on a Pi at least), just to rotate a JPEG image. Somehow I'm not too happy with that solution yet :/

Leaving this open until I have a better idea or OctoPrint needs to depend on Pillow anyhow for other reasons.

**Comment by crazyquark** [comment]
I have this too :)

**Comment by foosel** [comment]
ffmpeg... now that is an interesting idea. I wasn't aware that one can (ab)use it for image operations. That might work!

**Comment by tormentist** [comment]
How about -rot directly in mjpegstreamer?

**Comment by foosel** [comment]
That would be something that the user has to configure in mjpg-streamer per install. And if it even works depends completely on the camera. Also mjpg-streamer is not the only potential webcam server this plugin and OctoPrint have to work together with.

**Comment by crazyquark** [comment]
It is also possible to use the ImageMagick's convert command line tool that seems to be installed on OctoPi:
convert -rotate 180 pic.jpg pic.jpg

**Comment by crazyquark** [comment]
I see that the Telegram plugin already uses pillow for image manipulation.

**Comment by foosel** [comment]
Pillow is a huge dependency that I'd rather prefer to avoid pulling in only for rotating an image.

As a side note: If anyone wants to send a PR that uses ffmpeg for rotating the image as necessary, I'd be happy about that. I have my plate way too full with regular OctoPrint stuff to get around to do this myself in the foreseeable future I fear.

**Comment by crazyquark** [comment]
I wanted to that, but didn't get around to it. Would convert (the imagemagik utility) be ok as well?

**Comment by foosel** [comment]
Problem with convert is that while OctoPi might already ship with it, not everyone installing OctoPrint should be assumed to run that. I'd rather not introduce new dependencies if it can be avoided. Ffmpeg is already somewhat a dependency of core OctoPrint given that it's what's used for timelapse rendering, and the path for that would already be configured in the system.

**Comment by crazyquark** [comment]
allright, will try that

**Comment by crazyquark** [comment]
Made the changes but not creating a PR yet since I need to test them.
This is the code:
https://github.com/crazyquark/OctoPrint-Pushbullet/blob/master/octoprint_octobullet/__init__.py#L229

**Comment by foosel** [comment]
Without having tested it but just from a first look: Looks good!

Some small things:
  * I'd only try to flip/rotate/whatever if you DO have a valid ffmpeg path. You fetch it but you don't test if it's set and can be executed. At least you should check if it's set before going into your if
  * the "stolen from" comment is really not necessary, especially not considering the use of `global_get` is well documented ;)
  * use `global_get_boolean` instead of `global_get` for the flips and rotate variables
  * instead of a huge `if` around all the work, I'd suggest making an early bail instead:

    ```python
    def _process_image(path):
        # [get rotate, vflip, hflip, ffmpeg]

        if ffmpeg is None or not os.access(ffmpeg, os.X_OK) or (not vflip and not hflip and not rotate):
            return

        # [prepare command and fire]
    ```
