### ISSUE TITLE
competing PrintDone events

### ISSUE THREAD

**Issue by jeffeb3** [OctoPrint/OctoPrint-Pushbullet#4]
So, this isn't really an issue from the pushbullet plugin, but I made an event in the config to turn the light off at the end of a print. 

Pushbullet is also taking a pic at the end of the print, but it's losing the race, so I get images of a dark basement (no ghosts, yet, I'll let you know).

Any way to make my event happen after pushbullet takes a pic? 

Should I add a 5 second sleep to the light off call?

**Comment by Akex2** [comment]
Jeff do you are on marlin ?
I modify marlin with a custom command for do that

**Comment by foosel** [comment]
There's no way to control the order the events are triggered, so ideally what you'd want there is have the light-off handler *schedule* your light-off command at now + 5s or something (take a look at the linux `at` command for that). If you just add a blocking sleep to the script, you'll still have the competing events, your light handler going first might still happen, it will only run longer since the commands aren't executed asynchronously. Well, unless you tell it to, that would also work.

Anyway, not a bug. Mailing list or G+ Community would be a better place ;)

**Comment by jeffeb3** [comment]
I added the sleep yesterday, and it fixed it. Not sure why. I'll change to "at" though, I don't like blocking or races. 

Issues aren't just for bugs, but I should have done the mailing list.

Thanks.
